source('R/common.R')
x<-read_meta('metadata/table_catalog.csv');s<-load_catalog();m<-load_manifest()
header<-c('# Données bleues : élections provinciales québécoises','',
 'Dépôt autonome consacré aux données électorales officielles du Québec. La première version suit l’élection générale du 5 octobre 2026 et prépare l’archivage des résultats. Elle comprend des archives électorales, des résultats par bureau, les cartes, le financement et des compilations démographiques.','',
 paste0('État documentaire initial : 3 octobre 2026. Inventaire actuel : ',nrow(s),' sources identifiées, ',n_distinct(m$source_id),' sources récupérées. ',sum(x$visibility=='public'),' tables publiques et ',sum(x$visibility=='local_only'),' tables locales produites. Les captures et mises à jour peuvent faire évoluer ces nombres.'),'',
 '## Sources et droits','',
 'Les [données ouvertes](https://www.dgeq.org/donnees.html), leurs [archives](https://www.dgeq.org/archives.html) et leur [documentation](https://www.dgeq.org/documentation.html) constituent la source primaire. Les autres pages et documents proviennent d’Élections Québec et de l’Assemblée nationale. Les compléments ISQ, Statistique Canada et Données Québec sont inventoriés séparément. Les routes JSON supplémentaires sont celles réellement utilisées dans le JavaScript public des pages historiques.','',
 'Les conditions varient par fichier. Les adaptations financières, démographiques et certaines archives supplémentaires sont reconstructibles localement et exclues de Git, car leurs droits d’adaptation publique ne sont pas confirmés. Lire [DATA_LICENSES.md](DATA_LICENSES.md), le [catalogue des sources](metadata/source_catalog.csv) et la [couverture détaillée](docs/coverage.md).','',
 'Comprend des données ouvertes octroyées sous la licence d’utilisation des données ouvertes du directeur général des élections disponible à l’adresse Web dgeq.org. L’octroi de la licence n’implique aucune approbation par le directeur général des élections de l’utilisation des données ouvertes qui en est faite.','',
 '## Tables produites','',
 'Une ligne de table peut représenter une observation à une capture donnée. Utiliser `R/read_tables.R` pour sélectionner la dernière capture par événement et source. Les CSV importants sont comprimés en gzip, lisibles directement avec readr ou pandas. Les copies pédagogiques sont sous `data/processed/teaching`.','',
 '| Table | Grain | Période | Source | Format | Mise à jour | Lignes | Accès |','|---|---|---|---|---|---|---:|---|')
rows<-vapply(seq_len(nrow(x)),function(i){r<-x[i,];period<-r$period;if(nchar(period)>90)period<-'voir catalogue des tables';paste0('| `',r$table,'` | ',gsub('[|]','/',r$grain),' | ',period,' | ',ifelse(grepl('assnat',r$table),'Assemblée nationale','Élections Québec'),'; voir provenance | ',r$format,' | acquisition réussie | ',r$rows,' | ',ifelse(r$visibility=='public',paste0('[fichier](',r$path,')'),'reconstruction locale'),' |')},character(1))
footer<-c('', 'Les géométries officielles sont également diffusées en GeoPackage et en GeoJSON simplifié sous `data/processed/geography`. Le dictionnaire couvre les tables canoniques; les copies pédagogiques gardent les mêmes colonnes et définitions.','',
 '## Reconstruire','', 'R 4.5.0, dépendances dans `renv.lock`, Python 3 et bibliothèques système GIS. Poppler et Tesseract français servent aux documents financiers locaux.','',
 '```r','install.packages("renv")','renv::restore()','```','', '```sh','make all','make test','```','',
 'La [documentation de reproduction](docs/reproducibility.md) décrit le cache, la reconstruction hors ligne et les dépendances. Les nouvelles consultations ne reconstituent pas les anciennes captures perdues.','',
 '## Exemple R','', 'Exécuter depuis la racine du dépôt.','', '```r','library(readr)','library(dplyr)','library(ggplot2)','source("R/read_tables.R")','', 'candidates <- read_electoral_table("candidates")','counts <- candidates |> count(district_id, name = "n_candidates")','ggplot(counts, aes(n_candidates)) +','  geom_histogram(binwidth = 1, boundary = .5) +','  labs(x = "Nombre de candidatures", y = "Circonscriptions") +','  theme_minimal()','```','',
 'Les [exemples complets](examples) couvrent participation historique, géographie avec sf et données locales.','',
 '## Exemple Python','', '```python','import pandas as pd','import geopandas as gpd','', 'candidates = pd.read_csv("data/processed/candidates.csv", encoding="utf-8")','latest = candidates.groupby("source_id")["observed_at"].transform("max")','candidates = candidates.loc[candidates["observed_at"].eq(latest)]','counts = candidates.groupby("district_id").size().rename("n_candidates")','map_qc = gpd.read_file("data/processed/geography/districts_2026.gpkg")','joined = map_qc.merge(counts, on="district_id", validate="one_to_one")','print(joined[["district_id", "n_candidates"]].head())','```','',
 '## Actualisation et résultats 2026','',
 'Le workflow prévoit une acquisition quotidienne avant le scrutin, des captures toutes les quinze minutes pendant la fenêtre du dépouillement et une fréquence hebdomadaire ensuite. Les captures fréquentes cessent dès que la dernière capture est explicitement finale. Les horaires GitHub ne garantissent pas une cadence exacte. Les captures de résultats sont immuables sous `data/snapshots/results_2026`. Le récupérateur refuse les URLs de simulation avant l’ouverture officielle du 5 octobre à 20 h, America/Toronto.','',
 'Aucune donnée fictive de résultats 2026 n’est diffusée avant publication. Le statut final vient uniquement d’un indicateur officiel explicite. Un taux de bureaux renseignés de 100 % ne suffit pas. Le taux provincial extrapolé du producteur reste un champ source distinct du taux observé. Aucune projection ni recommandation électorale n’est produite.','',
 '## Qualité, provenance et limites','',
 'Les contrôles portent sur les identifiants, les captures, les sommes de votes, les bulletins, les ratios, les dates, les fractions spatiales et les chemins de diffusion. Le [dernier rapport](metadata/validation_latest.csv) décrit leur état; le [journal](metadata/quality_report.csv) conserve aussi les erreurs rencontrées pendant les lectures initiales. Les [résolutions](metadata/quality_resolutions.csv) distinguent les problèmes corrigés des points encore ouverts.','',
 'Chaque observation porte `source_id`, `snapshot_id`, `observed_at`, `retrieved_at`, `source_updated_at` et `data_status`. Le [dictionnaire](metadata/data_dictionary.csv), la [provenance](metadata/provenance.csv) et le [manifeste](metadata/acquisition_manifest.csv) relient tables, variables, captures, octets sources et scripts.','',
 'Les en-têtes de bureaux sans lien exact restent non résolus. Une intersection territoriale ne répartit ni personnes ni votes. Les totaux annuels personne-entité des contributions ne sont pas des versements individuels, et leur date de campagne n’est pas une date de don. Les bilans, flux et dépenses issus des autres PDF gardent une couverture de validation partielle. Les rapports préélectoraux 2026 ne sont pas encore disponibles dans la source consultée.','',
 'L’inventaire est systématique sur les index explorés et extensible; il ne prouve pas l’exhaustivité absolue de toutes les institutions. Les ressources inventoriées ne sont pas toutes téléchargées ni toutes normalisées. Le [modèle](docs/data_model.md) et la [politique de minimisation](docs/privacy.md) explicitent les choix.','',
 '## Enseignement et contribution','',
 '[Trente activités pédagogiques](docs/teaching_ideas.md) précisent niveaux, questions, tables et pièges. Lire [CONTRIBUTING.md](CONTRIBUTING.md) et [CODE_OF_CONDUCT.md](CODE_OF_CONDUCT.md). Le code est sous MIT; les données gardent leurs droits propres. Utiliser `CITATION.cff` et citer chaque producteur officiel ainsi que la capture utilisée.')
writeLines(c(header,rows,footer),'README.md',useBytes=TRUE)
